### PR TITLE
fix: ensure reward fees are only transferred if the reward token is set

### PR DESCRIPTION
**Pull request by jparklev**

### CODE REVIEW

**Review by stevenvaleri — APPROVED** [review]
The only alternative to consider would be using a safeTransfer that has this check included. That would be a significant dependency shift, and given the audits already performed, I think this solution makes sense.

All instances of rewardToken.safeTransfer are protected by an is 0 check and there's a test-case for each expected error ✅

**Comment by jparklev** [comment]
> The only alternative to consider would be using a safeTransfer that has this check included. That would be a significant dependency shift, and given the audits already performed, I think this solution makes sense.
> 
> All instances of rewardToken.safeTransfer are protected by an is 0 check and there's a test-case for each expected error ✅

Looking at this again, i wonder if we should actually not revert on collect fees but instead just skip the reward transfer. That way we could still collect pToken fees. What do you think @stevenvaleri?

**Comment by stevenvaleri** [comment]
> Looking at this again, i wonder if we should actually not revert on collect fees but instead just skip the reward transfer. That way we could still collect pToken fees. What do you think @stevenvaleri?

that's a very good idea. in addition to avoiding the issue identified where the rewardToken is set from an address to zero, it enables collecting pTokens fees for points that just don't have a redemption token yet.

**Comment by jparklev** [comment]
> it enables collecting pTokens fees for points that just don't have a redemption token ye

I think this case would be safe regardless, since you can't accrue reward token fees until a reward token is added, so main concern is just when it's added, then removed still ~

**Comment by jparklev** [comment]
How does this look @stevenvaleri? https://github.com/sense-finance/point-tokenization-vault/pull/36/commits/8dc5fee45cc61e07bd4e5b72113eefe948f2c0bf

**Comment by stevenvaleri** [comment]
> How does this look @stevenvaleri? [8dc5fee](https://github.com/sense-finance/point-tokenization-vault/commit/8dc5fee45cc61e07bd4e5b72113eefe948f2c0bf)

looks good

**Pull request merged**
